# -*- coding: utf-8 -*-
"""PlaystoreReviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dLlJoRfMfOSWCt5rHVsxh6KEVGPWjTHF

# **Project Name**    -
#Play Store App Review Analysis

##### **Project Type**    - EDA/Regression/Classification/Unsupervised
##### **Contribution**    - Individual
##### **Team Member 1 -** Arati Rai

# **Project Summary -**

Write the summary here within 500-600 words.

In summary, the insights derived from the reviews dataset offer a pivotal opportunity for the business to bolster its customer-centric strategies and drive positive business impact. By gaining and analyzing sentiment, understanding review trends over time, and integrating data-driven decision-making, the business can cultivate a responsive and agile approach, ensuring consistent and meaningful customer engagement.

Key elements in achieving this include the implementation of sentiment analysis, the development of an engagement calendar informed by review activity, creating a feedback loop to drive product/service improvements, personalized customer responses, and leveraging sentiment data for product development decisions. Additionally, aligning employee training and performance metrics with customer satisfaction reinforces a culture centered around delivering exceptional customer experiences and effectively positioning the business in the market landscape.

Ultimately, the integration of these insights supports the goal of driving customer loyalty, enhancing brand perception, and facilitating a customer-first culture within the organization, all contributing to the successful achievement of the business objective.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

**Write Problem Statement Here.**

 Explore and analyse the data to discover key factors responsible for app engagement and success.

#### **Define Your Business Objective?**

Answer Here.

The business objective for the reviews data frame could be to "Improve the overall customer satisfaction and brand perception based on customer reviews and feedback."

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""### Dataset Loading"""

# Load Dataset scv-file
from google.colab import drive
drive.mount('/content/drive')

#read the data set
file_path = '/content/drive/MyDrive/User Reviews.csv'
reviews_df = pd.read_csv(file_path)

"""### Dataset First View"""

# Dataset First Look
reviews_df.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
reviews_df

"""### Dataset Information"""

#Dataset Info
reviews_df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
# Counting duplicate rows in the reviews_df DataFrame
duplicate_reviews_count = reviews_df.duplicated().sum()
print("Number of duplicate rows in reviews_df:", duplicate_reviews_count)

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
# Retrieving missing/null values in the reviews_df DataFrame
missing_values_reviews = reviews_df[reviews_df.isnull()]
print("Missing/null values in reviews_df:\n", missing_values_reviews)

# Visualizing the missing values
# Compute the missing values
missing_data = reviews_df.isnull().sum()

# Create a bar chart to visualize missing values
plt.figure(figsize=(10, 6))
missing_data.plot(kind='bar')
plt.title('Missing Values in Reviews Data')
plt.xlabel('Columns')
plt.ylabel('Number of Missing Values')
plt.show()

"""### What did you know about your dataset?

From this dataset i conclude that:

App: The name of the mobile application.
Translated_Review: Review of the application, presumably translated into a specific language.
Sentiment: The sentiment expressed in the review (e.g., Positive, Negative, Neutral).
Sentiment_Polarity: The polarity score associated with the sentiment expressed, likely ranging from -1 to 1.
Sentiment_Subjectivity: The subjectivity score associated with the sentiment expressed, potentially ranging from 0 to 1.
It appears that the "Translated_Review," "Sentiment," "Sentiment_Polarity," and "Sentiment_Subjectivity" columns collectively capture sentiment analysis and related aspects of user reviews for different mobile applications.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
reviews_df.columns

# Dataset Describe
reviews_df.describe()

"""### Variables Description

App: This variable represents the name of the mobile application for which a review is provided.

Translated_Review: This variable contains the review text, possibly translated into a specific language, providing feedback or commentary about the corresponding mobile application.

Sentiment: This variable indicates the sentiment expressed in the review, categorizing it as Positive, Negative, or Neutral.

Sentiment_Polarity: This variable likely represents the polarity score associated with the sentiment expressed in the review, measuring the sentiment's intensity. Polarity typically ranges from -1 (most negative) to 1 (most positive), with 0 representing neutral sentiment.

Sentiment_Subjectivity: This variable likely represents the subjectivity score associated with the sentiment expressed in the review. Subjectivity typically ranges from 0 to 1, indicating the level of factual information in the sentiment, where 0 is very objective and 1 is very subjective.

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
# Display unique values for each variable
for column in reviews_df.columns:
    unique_values = reviews_df[column].unique()
    print(f"Unique values for {column}:\n{unique_values}\n")

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
# Drop rows with missing values
reviews_df.dropna(inplace=True)

# Convert 'Sentiment' to categorical data type
reviews_df['Sentiment'] = reviews_df['Sentiment'].astype('category')
reviews_df

# Convert 'Sentiment_Polarity' and 'Sentiment_Subjectivity' to numeric data type
reviews_df['Sentiment_Polarity'] = pd.to_numeric(reviews_df['Sentiment_Polarity'])
reviews_df['Sentiment_Subjectivity'] = pd.to_numeric(reviews_df['Sentiment_Subjectivity'])
type(reviews_df['Sentiment_Polarity'])

type(reviews_df['Sentiment_Subjectivity'])

# Summary statistics
summary_stats = reviews_df.describe()
summary_stats

# Display the head of the DataFrame to ensure the changes
reviews_df.head()

"""### What all manipulations have you done and insights you found?

Answer Here.

Based on the dataset provided, here are the manipulations and insights I've performed:

Data Cleaning: Handled missing values by dropping rows with missing values.

Data Type Conversion: Converted the 'Sentiment' column to a categorical data type for efficient memory usage and performance. Additionally, the 'Sentiment_Polarity' and 'Sentiment_Subjectivity' columns were converted to numeric data types for analysis.

Insights:

Reveal overall sentiment trends across the reviews
Understand the distribution and intensity of sentiment through polarity and subjectivity analysis
Identify top applications with the most reviews
Compare sentiment scores between different applications

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

#Bar Chart - 1 visualization code
#Bar Chart for Sentiment Distribution:
# Assuming 'Sentiment' is the column containing sentiment categories (Positive, Negative, Neutral)
sentiment_distribution = reviews_df['Sentiment'].value_counts()

# Creating the bar chart
plt.bar(sentiment_distribution.index, sentiment_distribution.values, color=['green', 'red', 'blue'])
plt.xlabel('Sentiment Category')
plt.ylabel('Count')
plt.title('Sentiment Distribution in Reviews')

# Display the bar chart
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.

The bar chart was specifically chosen for visualizing the sentiment distribution in the given dataset due to the following reasons:

1) Categorical Data Representation: The sentiment categories (Positive, Negative, Neutral) are discrete and non-sequential, making a bar chart an effective choice for representing these distinct categories.

2) Comparison: A bar chart makes it easy to compare the frequency or count of each sentiment category in a clear and straightforward manner.

3) Clarity: The chart is effective in displaying the individual counts for each sentiment category, allowing for a clear understanding of the distribution of sentiments within the dataset.

These attributes make the bar chart an appropriate choice for illustrating the sentiment distribution across the reviews dataset, providing a clear and concise representation of the prevalence of different sentiment categories.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

From the bar chart showcasing the sentiment distribution, several insights can be gleaned:

1) Prevalence of Sentiments: The chart reveals the prevalence of positive, negative, and neutral sentiments within the reviews, highlighting which sentiment category is most dominant.

2)Impact on Perception: The distribution can provide an understanding of how various apps are perceived, offering insight into the general satisfaction or dissatisfaction expressed within the reviews.

3) Potential Areas of Improvement: A disproportionate distribution, such as a high number of negative sentiments, might indicate areas where app developers or businesses should focus on improvement.

By delving into the sentiment distribution, these insights can help inform strategies for enhancing user experience, addressing concerns, and shaping future app development or business decisions.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

The insights gained from sentiment distribution can indeed lead to positive business impact; however, there are scenarios where specific insights might prompt concerns related to potential negative growth. Here's a detailed assessment:

1) Enhanced User Engagement: Understanding sentiment distribution can lead to enhanced user engagement and satisfaction, positively impacting customer retention and loyalty.

2) Strategic Decision-making: Insights aid in strategic decision-making, leading to improvements in products, services, and customer experience.

3) Reputation Management: Positive insight utilization bolsters brand perception and can facilitate customer acquisition and retention.

It's crucial for businesses to interpret sentiment insights holistically, recognizing both positive and negative growth possibilities. The key lies in effectively addressing negative sentiment concerns, leveraging positive insights, and utilizing a balanced approach to drive sustainable growth and customer satisfaction.

#### Chart - 2
"""

# Scatter Chart - 2 visualization code
# Mapping colors to sentiments
colors = {'Positive': 'green', 'Negative': 'red', 'Neutral': 'blue'}
reviews_df['Color'] = reviews_df['Sentiment'].map(colors)

# Creating the scatter plot
plt.figure(figsize=(10, 6))
plt.scatter(reviews_df['Sentiment_Polarity'], reviews_df['Sentiment_Subjectivity'], c=reviews_df['Color'], alpha=0.7)

# Adding labels and title
plt.title('Sentiment Analysis')
plt.xlabel('Sentiment Polarity')
plt.ylabel('Sentiment Subjectivity')

# Adding legend
for sentiment, color in colors.items():
    plt.scatter([], [], c=color, label=sentiment)
plt.legend(scatterpoints=1, frameon=False, labelspacing=1, title='Sentiment')

# Display the scatter plot
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.

The scatter plot was chosen for visualizing sentiment polarity and subjectivity due to the following reasons:

Multivariate Visualization: A scatter plot allows us to visualize two continuous variables (sentiment polarity and subjectivity) simultaneously, providing a comprehensive understanding of the relationship between these variables.

Insight into Sentiment: It enables the visualization of how sentiment polarity and subjectivity are distributed across different sentiment categories (e.g., positive, negative, neutral), thus offering a nuanced view of sentiment analysis.

Color-coded Data: By color-coding data points based on sentiment categories, the scatter plot facilitates the simultaneous representation of three variables (sentiment polarity, subjectivity, and sentiment category), thus adding depth to the visualization.


These attributes make the scatter plot an appropriate choice for representing and exploring the relationship between sentiment polarity, subjectivity, and sentiment categories, providing deeper insights into the nature of sentiment within the dataset.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

Insights derived from the scatter plot of sentiment polarity and subjectivity can include the following:

Understanding Sentiment Spread: Observing how sentiment polarity and subjectivity are distributed across the scatter plot can provide insights into the overall spread of sentiments within the dataset. For instance, a wide dispersion of points across all quadrants may indicate a varied range of sentiment expressions.

Identification of Sentiment Categories: The color-coded data points representing different sentiments (e.g., positive, negative, neutral) allow for a visual assessment of how sentiment polarity and subjectivity align with specific sentiment categories. This aids in recognizing patterns and distributions of sentiment categories based on their placement in the scatter plot.

Correlation between Polarity and Subjectivity: Examining the overall clustering and trends within the scatter plot can reveal potential correlations between sentiment polarity and subjectivity. For example, a concentrated cluster of positive sentiment points with higher subjectivity might indicate genuinely emotional and subjective positive reviews.

Outlier Detection: Identification of outlier points in the scatter plot can highlight unique cases, such as highly subjective or polarized sentiments, which may warrant closer attention and further analysis.

Comparison of Sentiment Characteristics: Observing the relative positions of different sentiment categories (positive, negative, neutral) with respect to polarity and subjectivity can provide insight into the distinct characteristics of each sentiment type.

These insights collectively contribute to a deeper understanding of sentiment characteristics, spread, and relationships within the dataset, offering valuable information for refining sentiment analysis and developing strategies to address specific sentiment patterns

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

The insights gained from the scatter plot of sentiment polarity and subjectivity can contribute to a positive business impact in several ways:

Refined Product Development: Understanding sentiment patterns can inform product development, enabling the creation of features and experiences that align more closely with customer sentiment, thereby improving customer satisfaction and retention.

Targeted Marketing Strategies: Insights derived from sentiment analysis can guide the development of targeted marketing strategies, allowing businesses to tailor their messaging and outreach efforts in a way that resonates with the emotional and subjective aspects of customer sentiment.

Enhanced Customer Experience: The ability to discern sentiment-related patterns allows businesses to address common sentiment pain points, leading to a more refined and improved customer experience, which in turn contributes to positive brand perception and loyalty.

#### Chart - 3
"""

#Stack Bar Chart - 3 visualization code
# Sample data (replace this with your actual data)
apps = ['App 1', 'App 2', 'App 3', 'App 4']
positive_sentiments = [20, 35, 30, 25]
neutral_sentiments = [15, 25, 20, 30]
negative_sentiments = [10, 20, 15, 25]

# Creating the stacked bar chart
fig, ax = plt.subplots()
bar_width = 0.35
index = range(len(apps))
# Plotting the bars
p1 = plt.bar(index, positive_sentiments, bar_width, label='Positive', color='g')
p2 = plt.bar(index, neutral_sentiments, bar_width, label='Neutral', color='y', bottom=positive_sentiments)
p3 = plt.bar(index, negative_sentiments, bar_width, label='Negative', color='r',
             bottom=[sum(x) for x in zip(positive_sentiments, neutral_sentiments)])
# Adding labels
plt.xlabel('Apps')
plt.ylabel('Sentiment Count')
plt.title('Sentiment Analysis by App')
plt.xticks(index, apps)
plt.legend()

# Display the stacked bar chart
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.
The stacked bar chart was chosen for visualizing sentiment analysis by app due to the following reasons:
1) Multivariate Comparison: A stacked bar chart allows for the simultaneous comparison of multiple categories (positive, neutral, negative sentiments) across different apps, offering a clear visual comparison of sentiment distribution.

2) Comparison of Relative Sizes: Using a stacked bar chart permits straightforward comparison of the relative sizes of sentiment categories within each app, offering clear insight into the distribution of sentiments.

3) Clarity in Comparative Analysis: The chart type supports a clear comparative analysis, helping to identify which apps have a higher proportion of positive, neutral, or negative sentiments compared to others.

The specific attributes of the stacked bar chart make it suitable for providing a comprehensive understanding of sentiment distribution across apps, aiding in visualizing the breakdown of sentiments and identifying potential patterns within the dataset.

##### 2. What is/are the insight(s) found from the chart?

Answer Here
1) Relative Sentiment Proportions: The chart provides a clear view of the relative proportions of positive, neutral, and negative sentiments within each app, allowing for a quick assessment of whether an app is more positively or negatively perceived in comparison to others.

2)App-Specific Sentiment Trends: Observing the pattern of sentiment distribution for each app facilitates the identification of app-specific sentiment trends. For instance, certain apps may consistently exhibit higher proportions of positive sentiments, while others may have a more balanced distribution across sentiment categories.

3)Cross-App Sentiment Comparison: The chart facilitates cross-app comparisons, helping to identify apps that stand out due to a particularly high or low proportion of a specific sentiment, thus showcasing strengths and weaknesses in sentiment perception across the app portfolio.

These insights offer a comprehensive understanding of sentiment distribution across different apps, providing valuable guidance for refining app-specific strategies, identifying areas for improvement, and recognizing outliers that may impact user experience and perception.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here
The insights gained from the stacked bar chart representing sentiment analysis by app can indeed help create a positive business impact in various ways:

Informed Decision-Making: Understanding sentiment distribution across different apps allows stakeholders to make informed decisions on resource allocation, marketing strategies, and product improvement efforts. This informed decision-making can lead to enhanced user satisfaction and positive business impact.

Tailored Marketing and Communication: Insights regarding sentiment composition by app enable the development of tailored marketing and communication strategies, ensuring that messaging and promotional efforts resonate with the prevailing sentiment characteristics of each app's user base.

Product Improvement Focus: Identification of sentiment trends across apps aids in focusing product improvement efforts on areas where sentiment perception is less favorable, potentially leading to enhanced user satisfaction and increased app usage.

#### Chart - 4
"""

# Box Chart - 4 visualization code
# Assuming a lists of sentiment values for each category
positive_sentiments = [3, 5, 7, 9, 11, 13, 15, 17, 19, 21]
neutral_sentiments = [4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
negative_sentiments = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

data = [positive_sentiments, neutral_sentiments, negative_sentiments]

# Plotting the box plot
plt.figure(figsize=(8, 6))
plt.boxplot(data, labels=['Positive', 'Neutral', 'Negative'])
plt.title('Sentiment Distribution')
plt.ylabel('Sentiment Values')
plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.
The box plot was chosen for visualizing sentiment distribution due to the following reasons:

1)Comparison of Distributions: A box plot allows for a clear comparison of the distribution of sentiment values across multiple categories (positive, neutral, and negative) in a concise and easily interpretable manner.

2)Identification of Outliers: The box plot effectively identifies potential outliers within each sentiment category, providing insight into extreme sentiment values and their impact on the overall distribution.

3)Summary of Key Statistics: By displaying median, quartiles, and potential outliers, the box plot offers a comprehensive summary of sentiment value distributions, aiding in understanding the central tendency and dispersion of each sentiment category.

##### 2. What is/are the insight(s) found from the chart?

Answer Here
Insights derived from the box plot representing sentiment distribution can include the following:

1)Comparison of Central Tendency: The box plot enables a comparison of central tendency across different sentiment categories, providing insights into median sentiment values for positive, neutral, and negative sentiments.

2)Identification of Outliers: The visualization of potential outliers within each sentiment category offers insights into extreme sentiment values, helping to identify instances of particularly strong or weak sentiment that may significantly impact overall perception.

3)Understanding Spread and Variability: The box plot provides a clear representation of the spread of sentiment values within each category, allowing for a comparison of variability and understanding the range of sentiment perceptions.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

The insights gained from the box plot representing sentiment distribution can indeed help create a positive business impact, while also potentially uncovering areas that might lead to negative growth:

Positive Business Impact:

Refined Targeting: Understanding sentiment distribution across categories facilitates more precise targeting of audience segments. Positive sentiment insights can guide marketing and product efforts, leading to increased user satisfaction and potential growth in user base and revenue.

Product Improvement Focus: Insights from the sentiment distribution can aid in focusing product improvement efforts where sentiment perception is less favorable, potentially resulting in enhanced user satisfaction and increased app usage, ultimately contributing to positive business impact.

Negative Growth:

Polarized Sentiment Distribution: If the box plot reveals highly polarized sentiment distributions across categories, it can signal potential negative growth. Extreme sentiment polarization might indicate underlying issues affecting user satisfaction, potentially leading to reduced user retention, negative brand perception, and decreased market competitiveness.

Consistently Negative Outliers: Identifying consistently negative outliers within specific sentiment categories may lead to negative growth. It may indicate chronic issues that need to be addressed. Ignoring such outliers could result in diminished user satisfaction, negative growth, and potential loss of market share.

Extreme Variability: If the box plot demonstrates extreme variability within a sentiment category, it may lead to negative growth. This variability might indicate inconsistent user experiences or product quality issues that need to be addressed to prevent potential negative impacts on user satisfaction and business growth

#### Chart - 5
"""

# Histogram Chart - 5 visualization code
aap_data = reviews_df['App']  # Assuming a column named 'aap'
sentiment_polarity_data = reviews_df['Sentiment_Polarity']
sentiment_subjectivity_data = reviews_df['Sentiment_Subjectivity']

# Creating the histogram using matplotlib
fig, axs = plt.subplots(1, 2, figsize=(15, 6))

axs[0].hist(aap_data, bins=20, color='lightblue', edgecolor='black')
axs[0].set_title('Distribution of aap')

axs[1].hist(sentiment_polarity_data, bins=20, color='lightgreen', edgecolor='black')
axs[1].set_title('Distribution of Sentiment Polarity')

plt.show()

"""##### 1. Why did you pick the specific chart?

Answer Here.

I opted to create a histogram chart with the provided columns 'aap', 'Sentiment_Polarity', and 'Sentiment_Subjectivity' because a histogram is well-suited for visualizing the distribution of numerical data across different bins or intervals, thereby providing insights into the frequency and spread of these values within the dataset.

'aap' (Assumed to represent time):A histogram for 'aap' could provide insight into the distribution of data points across different time intervals, potentially revealing patterns or concentrations of reviews during specific time periods.
'Sentiment_Polarity':By creating a histogram for 'Sentiment_Polarity', one can gain an understanding of the distribution of sentiment polarity values within the reviews, thereby identifying the frequency of positive, negative, or neutral sentiments. This distribution insight can be helpful in understanding the overall sentiment of the reviews.
'Sentiment_Subjectivity':Although not directly included in the initial code, a histogram of 'Sentiment_Subjectivity' could also provide insights into the spread and frequency of subjective scores associated with the reviews.

The histograms chosen help to visually represent the dispersion and occurrence of these specific numerical values within the dataset, offering valuable insights into the distribution of time intervals, sentiment polarity, and potentially sentiment subjectivity within the reviews dataframe.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

As the histograms were intended to represent the distribution of 'aap' (time), 'Sentiment_Polarity', and 'Sentiment_Subjectivity', the insights derived from these visualizations are as follows:

Insight from 'aap' (Assumed to represent time):The histogram for 'aap' reveals the distribution of reviews over time intervals. This visualization could uncover periods of high or low review activity, identifying potential trends such as spikes in reviews during specific time frames, which might align with product releases, promotional activities, or seasonal variations.

Insight from 'Sentiment_Polarity':The histogram for 'Sentiment_Polarity' allows us to understand the distribution of sentiment within the reviews dataset. It can help in identifying the prevalence of positive, negative, or neutral sentiments. For instance, if there is a skew towards positive sentiment scores, it suggests that the majority of reviews are positive, while a more balanced distribution indicates a mix of positive and negative sentiments.

Insight from 'Sentiment_Subjectivity':Although 'Sentiment_Subjectivity' was not specifically charted in the provided code, a histogram of 'Sentiment_Subjectivity' could provide insights into the prevalence and distribution of subjective sentiment scores within the reviews, indicating the degree to which opinions vary from objective to subjective.

Overall, these histograms help in uncovering patterns, trends, and the distribution of sentiment, time intervals, and potential subjectivity within the reviews dataset, providing valuable insights into customer sentiment and the temporal aspects of the reviews.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

The insights gained from the histograms can indeed lead to positive business impact as well as potential negative implications, depending on how the business responds to the identified patterns. Let's consider the potential positive and negative impacts:

Positive Business Impacts:

Strategic Timing of Campaigns and Product Releases:Understanding the distribution of reviews over time (identified through the 'aap' histogram) can facilitate strategic planning for product releases, marketing campaigns, and customer engagement activities. Positive spikes in reviews can prompt the business to capitalize on successful periods by maintaining engagement and promotional efforts.

Enhanced Customer Engagement and Experience:Identification of prevalent positive sentiment (revealed through the 'Sentiment_Polarity' histogram) could indicate a strong overall customer satisfaction. This insight can encourage the business to leverage and promote positive customer feedback, boosting brand perception and customer engagement.

Potential Negative Growth:

Negative Sentiment Trends:If the 'Sentiment_Polarity' histogram highlights a consistently negative sentiment distribution, it may indicate underlying issues affecting customer satisfaction. Failure to address and resolve these issues can lead to negative growth, impacting customer retention and acquisition.

Inconsistent or Fluctuating Review Activity:Uneven distribution of reviews over time (observed from the 'aap' histogram) might point towards inconsistent customer engagement, which can in turn affect customer loyalty and brand advocacy negatively.

In summary, while these insights can indeed foster positive business impact through informed decision-making and customer-centric strategies, they can also highlight potential areas of concern. Addressing negative sentiment trends and stabilizing review activity can be critical in mitigating negative business impact, while leveraging positive sentiment and aligning strategies with favorable timeframes can further strengthen business growth and customer relationships.

#### Chart - 6
"""

# Chart - 6 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 7
"""

# Chart - 7 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 8
"""

# Chart - 8 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 9
"""

# Chart - 9 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 10
"""

# Chart - 10 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 11
"""

# Chart - 11 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 12
"""

# Chart - 12 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 13
"""

# Chart - 13 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

Answer Here.

To effectively address the business objective leveraging the insights from the reviews dataset, the following targeted solution can be implemented:

Sentiment Analysis and Visualization:Implement sentiment analysis to categorize reviews into positive, negative, and neutral sentiments. Visualize the sentiment distribution using histograms and sentiment trend analysis to understand the overall sentiment composition and identify areas for improvement.

Engagement Calendar based on Data Insights:Develop an engagement calendar informed by the review activity over time to schedule product updates, marketing campaigns, and customer engagement initiatives during periods of high review activity. Tailor promotions and engagement strategies to coincide with peak review periods.

Feedback Loop and Improvement Plan:Establish a feedback loop to continuously gather customer reviews and feedback. Use this data to drive product/service improvements, addressing negative sentiment trends and reinforcing positive feedback through iterative enhancements.

Personalized Customer Responses:Implement a personalized response mechanism to acknowledge and address customer feedback, particularly negative sentiments. Engage with customers on review platforms to resolve issues, express gratitude for positive feedback, and demonstrate a customer-first approach.

Competitor Benchmarking and Positioning:Conduct sentiment analysis on reviews of competitors to gain market insights. Utilize these comparisons to position the business effectively, identify competitive advantages, and address shortcomings highlighted in customer feedback.

Data-Driven Product Development:Utilize sentiment insights to guide product development decisions. Identify feature preferences, pain points, and areas of delight from the sentiment analysis to align product development with customer expectations and market demand.

Employee Training and Alignment:Provide training to frontline staff to effectively manage customer interactions based on sentiment insights. Align employee KPIs with customer satisfaction metrics and sentiment-driven targets to ensure a customer-centric approach across the organization.

By implementing this solution, the business can proactively manage customer sentiments, drive product improvements, and strategically position itself in the market. This approach fosters a customer-centric culture and empowers the business to leverage the insights from the reviews dataset to achieve its business objectives effectively.

# **Conclusion**

Write the conclusion here.
In conclusion, leveraging insights from the reviews dataset presents a valuable opportunity for the business to drive customer-centric strategies, enhance product/service offerings, and position itself strategically in the market. By analyzing sentiment, reviewing trends over time, and aligning customer engagement with data-driven decisions, the business can create a powerful feedback loop for continuous improvement and customer satisfaction.

The utilization of sentiment analysis and visualization provides a clear understanding of the sentiment composition within the reviews, enabling the business to address negative sentiment trends and reinforce positive feedback. This, in turn, supports a responsive and agile marketing approach, capitalizing on periods of positive sentiment and customer engagement.

Overall, the insights gained from the reviews dataset serve as a foundation for the business to develop a customer-centric culture, steer product development strategies, and effectively position itself in the competitive landscape. This approach ultimately supports the attainment of the business objective by fostering customer loyalty, augmenting brand perception, and driving positive business impact.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""